version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: chat_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: chatdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nodeapp:
    build: ./server
    container_name: server_nodeapp
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/chatdb
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: chatdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      PORT: 3000

  client:
    build: ./client
    container_name: chat_client
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - nodeapp
    environment:
      VITE_API_URL: http://localhost:3000
    volumes:
      - ./client/src:/app/src

volumes:
  pgdata:
